modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
modId="lucky"
version="${version}"
displayName="Lucky Block"
authors="Alex Socha"
description="Adds a block with random outcomes."

[[dependencies.lucky]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
